"""Static mapping from each pipeline stage to the seven-layer travel-agent
maturity framework. This is fixed industry positioning information for the
dashboard to render as honest labels — it is not generated by any agent.

Layer 6 (hotel/airline/travel-agency internal operations agents) is a
B2B/supply-side capability this consumer-facing demo does not touch; it is
listed in the dashboard's legend as "not demonstrated" rather than mapped to
a stage.
"""
from typing import Optional, TypedDict


class StageMeta(TypedDict):
    layer: Optional[int]
    layer_name: str
    maturity: str
    note: str


STAGE_METADATA: dict[str, StageMeta] = {
    "inspiration": {
        "layer": 1,
        "layer_name": "旅遊靈感與目的地探索",
        "maturity": "高",
        "note": "真實網路搜尋，可信網域限定",
    },
    "itinerary": {
        "layer": 2,
        "layer_name": "個人化行程規劃與動態排程",
        "maturity": "高（草稿生成）",
        "note": "行程草稿生成成熟度高；動態重新排程見下方橋段",
    },
    "transportation": {
        "layer": 3,
        "layer_name": "搜尋、比價與交易 Agent",
        "maturity": "低（交易執行）",
        "note": "模擬資料，僅候選提案，不實際比價/下單",
    },
    "accommodation": {
        "layer": 3,
        "layer_name": "搜尋、比價與交易 Agent",
        "maturity": "低（交易執行）",
        "note": "模擬資料，僅候選提案，不實際比價/下單",
    },
    "dining": {
        "layer": 7,
        "layer_name": "目的地管理與觀光供給整合",
        "maturity": "中高",
        "note": "真實網路搜尋，可信網域限定",
    },
    "attractions": {
        "layer": 7,
        "layer_name": "目的地管理與觀光供給整合",
        "maturity": "中高",
        "note": "真實網路搜尋，可信網域限定",
    },
    "activities": {
        "layer": 3,
        "layer_name": "搜尋、比價與交易 Agent",
        "maturity": "低（交易執行）",
        "note": "模擬 KKday/Klook 風格候選，僅提案，不實際下單",
    },
    "shopping": {
        "layer": 7,
        "layer_name": "目的地管理與觀光供給整合",
        "maturity": "中",
        "note": "真實網路搜尋，可信網域限定",
    },
    "in_trip_guide": {
        "layer": 4,
        "layer_name": "旅途中即時助理與數位禮賓",
        "maturity": "中",
        "note": "個人化行中提醒，屬中成熟度",
    },
    "replanning": {
        "layer": 5,
        "layer_name": "異常處理與自動改訂",
        "maturity": "中（分析與提案）/ 低（跨平台自動改訂）",
        "note": "本 demo 僅示範單日行程層級的動態重排與人工確認，不涉及跨平台改票/改房",
    },
    "review": {
        "layer": None,
        "layer_name": "評價與分享（第一方資料回饋迴圈）",
        "maturity": "—",
        "note": "呼應媒體/平台定位建議：使用者回饋轉為第一方資料",
    },
}

REAL_SEARCH_STAGES = {"inspiration", "dining", "attractions", "shopping"}
SIMULATED_CANDIDATE_STAGES = {"transportation", "accommodation", "activities"}
